		<nav>
			<ul>
				<li><a href="index.php">Home</a></li>
				<li>Learn More
					<ul>
						<li><a href="stark.php">House Stark</a></li>
						<li><a href="targaryen.php">House Targaryen</a></li>
						<li><a href="lannister.php">House Lannister</a></li>
						<li><a href="greyjoy.[php]">House Greyjoy</a></li>
					</ul>
				</li>
				<li><a href="login.php">Admin Login</a></li>
			</ul>
		</nav>